[build]
target = "avr-specs/avr-atmega328p.json"

[test]
target = "stable-x86_64-unknown-linux-gnu"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno --open-console --baudrate 115200"

[unstable]
build-std = ["core"]
